services:
  nodejs:
    image: node:22
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MEILI_HOST=http://meilisearch:7700
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres_db
      - meilisearch
      - redis
    networks:
      - app_network
    command: [ "sh", "-c", "npm install && npx prisma migrate deploy && npm run build && npm run start:prod" ]

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - meili_data:/meili_data
    ports:
      - "7700:7700"
    networks:
      - app_network
    command: [ "meilisearch", "--db-path", "/meili_data" ]

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.yohocx.store/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/api.yohocx.store/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - nodejs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  meili_data:
