version: '3.9'

services:
  nodejs:
    image: node:22
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:root@postgres:5432/storage
      - MEILI_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - meilisearch
      - redis
    command: [ "sh", "-c", "npm install && npm run build && npm run start:prod" ]

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: storage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    restart: always
    environment:
      MEILI_NO_ANALYTICS: true
    ports:
      - "7700:7700"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
